# Generated by Django 2.2.8 on 2019-12-17 08:46

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SourceType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        help_text="Name of the source system",
                        max_length=200,
                        verbose_name="system",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        help_text="Type of the source",
                        max_length=200,
                        verbose_name="type",
                    ),
                ),
            ],
            options={
                "verbose_name": "source type",
                "verbose_name_plural": "source types",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "source_id",
                    models.CharField(
                        help_text="Unique identifier indicating the source",
                        max_length=200,
                        unique=True,
                        verbose_name="source identifier",
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(
                        help_text="Geometry of the feature",
                        srid=4326,
                        verbose_name="geometry",
                    ),
                ),
                (
                    "source_modified_at",
                    models.DateTimeField(
                        help_text="Time when the feature was modified in the source data",
                        verbose_name="source modified at",
                    ),
                ),
                (
                    "mapped_at",
                    models.DateTimeField(
                        help_text="Most recent time when the feature was mapped from the source data",
                        verbose_name="mapped at",
                    ),
                ),
                (
                    "source_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="features.SourceType",
                        verbose_name="source type",
                    ),
                ),
            ],
            options={
                "verbose_name": "feature",
                "verbose_name_plural": "features",
                "ordering": ("id",),
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="FeatureTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the feature",
                        max_length=200,
                        verbose_name="name",
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="features.Feature",
                    ),
                ),
            ],
            options={
                "verbose_name": "feature Translation",
                "db_table": "features_feature_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
