# Generated by Django 2.2.8 on 2019-12-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="featuretranslation",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="URL for more information about this feature",
                verbose_name="url",
            ),
        ),
    ]
