# Generated by Django 2.2.8 on 2019-12-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0002_featuretranslation_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="source_id",
            field=models.CharField(
                help_text="Identifier for the feature in the source",
                max_length=200,
                verbose_name="source identifier",
            ),
        ),
        migrations.AddConstraint(
            model_name="feature",
            constraint=models.UniqueConstraint(
                fields=("source_type", "source_id"), name="unique_source_feature"
            ),
        ),
    ]
