# Generated by Django 2.2.8 on 2020-01-15 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0006_featuretranslation_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "street_address",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="street address"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="postal code"
                    ),
                ),
                (
                    "municipality",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="municipality"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="phone number"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "feature",
                    models.OneToOneField(
                        help_text="Contact information for the given feature",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_info",
                        to="features.Feature",
                        verbose_name="feature",
                    ),
                ),
            ],
            options={
                "verbose_name": "contact info",
                "verbose_name_plural": "contact info",
                "ordering": ("id",),
            },
        ),
    ]
