# Generated by Django 3.0.2 on 2020-01-24 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
        ("features", "0008_add_models_for_opening_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Category the feature belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="features",
                to="categories.Category",
                verbose_name="category",
            ),
        ),
    ]
