# Generated by Django 3.0.2 on 2020-02-04 15:06

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0010_feature_parents"),
    ]

    operations = [
        migrations.CreateModel(
            name="Override",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "field",
                    models.CharField(
                        choices=[("NAME", "Name")],
                        help_text="Field that is overridden",
                        max_length=4,
                        verbose_name="field",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overrides",
                        to="features.Feature",
                        verbose_name="feature",
                    ),
                ),
            ],
            options={
                "verbose_name": "override",
                "verbose_name_plural": "overrides",
                "ordering": ("id",),
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="OverrideTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                (
                    "string_value",
                    models.TextField(
                        blank=True,
                        help_text="String value for the override",
                        verbose_name="text value",
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="features.Override",
                    ),
                ),
            ],
            options={
                "verbose_name": "override Translation",
                "db_table": "features_override_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name="override",
            constraint=models.UniqueConstraint(
                fields=("feature", "field"), name="unique_override_feature_field"
            ),
        ),
    ]
