# Generated by Django 3.0.3 on 2020-02-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0011_add_feature_overrides"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="sourcetype",
            constraint=models.UniqueConstraint(
                fields=("system", "type"), name="unique_source_type"
            ),
        ),
    ]
