# Generated by Django 3.0.3 on 2020-03-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0012_unique_source_type_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="visibility",
            field=models.SmallIntegerField(
                choices=[(1, "Visible"), (0, "Hidden")], default=1
            ),
        ),
    ]
