# Generated by Django 3.0.3 on 2020-03-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0013_feature_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="parents",
            field=models.ManyToManyField(
                blank=True,
                help_text="Parents of this feature (e.g. stops along a route etc.)",
                related_name="children",
                to="features.Feature",
                verbose_name="parents",
            ),
        ),
    ]
