# Generated by Django 3.0.3 on 2020-03-11 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0014_feature_parents_blank"),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        help_text="Type of the link",
                        max_length=200,
                        verbose_name="type",
                    ),
                ),
                ("url", models.URLField(max_length=2000, verbose_name="url")),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="features.Feature",
                        verbose_name="feature",
                    ),
                ),
            ],
            options={
                "verbose_name": "link",
                "verbose_name_plural": "links",
                "ordering": ("id",),
            },
        ),
        migrations.AddConstraint(
            model_name="link",
            constraint=models.UniqueConstraint(
                fields=("feature", "type"), name="unique_link_feature_type"
            ),
        ),
    ]
