# Generated by Django 3.0.3 on 2020-03-11 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0016_featuretag_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featuretag",
            name="feature",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feature_tags",
                to="features.Feature",
            ),
        ),
        migrations.AlterField(
            model_name="featuretag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feature_tags",
                to="features.Tag",
            ),
        ),
    ]
