# Generated by Django 3.0.3 on 2020-03-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0017_modify_feature_tag_related_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="featuretranslation",
            name="one_liner",
            field=models.CharField(
                blank=True,
                help_text="A short description limited to 64 chars",
                max_length=64,
                verbose_name="one-liner",
            ),
        ),
    ]
