# Generated by Django 3.0.3 on 2020-03-29 20:37

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0019_featureteaser_featureteasertranslation"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureDetails",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("HARBOR", "Harbor")],
                        help_text="What type of details are described in this object",
                        max_length=6,
                        verbose_name="type",
                    ),
                ),
                (
                    "data",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="data",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="features.Feature",
                        verbose_name="details",
                    ),
                ),
            ],
            options={
                "verbose_name": "feature details",
                "verbose_name_plural": "feature details",
                "ordering": ("id",),
            },
        ),
        migrations.AddConstraint(
            model_name="featuredetails",
            constraint=models.UniqueConstraint(
                fields=("feature", "type"), name="unique_feature_detail_type"
            ),
        ),
    ]
