# Generated by Django 3.0.3 on 2020-04-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_auto_20200415_1432"),
        ("features", "0021_pricetag_pricetagtranslation"),
    ]

    operations = [
        migrations.RemoveField(model_name="feature", name="category",),
        migrations.AddField(
            model_name="feature",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="features",
                through="categories.CategoriesTable",
                to="categories.Category",
                verbose_name="categories",
            ),
        ),
    ]
