# Generated by Django 3.0.3 on 2020-05-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0021_pricetag_pricetagtranslation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="visibility",
            field=models.SmallIntegerField(
                choices=[(0, "Hidden"), (1, "Visible"), (2, "Draft")], default=1
            ),
        ),
    ]
